./waf --run "scratch/fair_4 --DCR=false"
./waf --run "scratch/fair_8 --DCR=false"
./waf --run "scratch/fair_16 --DCR=false"
./waf --run "scratch/fair_20 --DCR=false"
./waf --run "scratch/fair_4 --DCR=true --sack=true"
./waf --run "scratch/fair_8 --DCR=true --sack=true"
./waf --run "scratch/fair_16 --DCR=true --sack=true"
./waf --run "scratch/fair_20 --DCR=true --sack=true"
./waf --run "scratch/fair_4_all --DCR=false"
./waf --run "scratch/fair_8_all --DCR=false"
./waf --run "scratch/fair_16_all --DCR=false"
./waf --run "scratch/fair_20_all --DCR=false"
./waf --run "scratch/fair_4_all --DCR=true --sack=true"
./waf --run "scratch/fair_8_all --DCR=true --sack=true"
./waf --run "scratch/fair_16_all --DCR=true --sack=true"
./waf --run "scratch/fair_20_all --DCR=true --sack=true"
